### ISSUE TITLE
Can't download VODS, errors out.

### ISSUE THREAD

**Issue by JaySebagh** [Franiac/TwitchLeecher#345]
Tried downloading vods from twitch.tv/imls but it keeps erroring out and not letting me download.

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 443284351
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/443284351
Crop Start: Yes (00:00:00)
Crop End: Yes (01:00:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\hackman\Downloads\20190623_443284351_Teamfight Tactics.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\hackman\AppData\Local\Temp\TL_ade13fce-1b47-43e7-a924-b1c4ec12f7dc

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561669124%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A443284351%7D
Signature: 018fa89f3520109e1284c960d78982b88be6c83a
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\hackman\AppData\Local\Temp\TL_ade13fce-1b47-43e7-a924-b1c4ec12f7dc'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\hackman\AppData\Local\Temp\TL_ade13fce-1b47-43e7-a924-b1c4ec12f7dc'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by uaxiii** [comment]
Yeah, i'm getting the same problem as well.

**Comment by garoto** [comment]
This specific VOD seems to be working for me:
```
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 443284351
Selected Quality: 1920x1080@60fps (Source)
Download Url: https://www.twitch.tv/videos/443284351
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: F:\Videos\downloading\LS- LCK Caster & Varus apologist tries out other methods to victory. Grinding a ton today_tmrw waiting for korean ranked ! Recording stats_20190623_imls-v443284351.mp4
FFMPEG Path: C:\Apps\Diversos\TwitchLeecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\redacted\AppData\Local\Temp\TL_699d28df-8cfd-468c-840b-8d839dbd4bd0

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1561727590%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A443284351%7D
Signature: e155ff0c7e63e38902297edf017bf0407f56a805
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\redacted\AppData\Local\Temp\TL_699d28df-8cfd-468c-840b-8d839dbd4bd0'... done!

Retrieving m3u8 playlist urls for all VOD qualities... done!
https://vod-secure.twitch.tv/ca0d74693a95fdfb6491_imls_34644912768_1233972804/chunked/index-dvr.m3u8
https://vod-secure.twitch.tv/ca0d74693a95fdfb6491_imls_34644912768_1233972804/720p60/index-dvr.m3u8
https://vod-secure.twitch.tv/ca0d74693a95fdfb6491_imls_34644912768_1233972804/720p30/index-dvr.m3u8
https://vod-secure.twitch.tv/ca0d74693a95fdfb6491_imls_34644912768_1233972804/480p30/index-dvr.m3u8
https://vod-secure.twitch.tv/ca0d74693a95fdfb6491_imls_34644912768_1233972804/audio_only/index-dvr.m3u8
https://vod-secure.twitch.tv/ca0d74693a95fdfb6491_imls_34644912768_1233972804/360p30/index-dvr.m3u8
https://vod-secure.twitch.tv/ca0d74693a95fdfb6491_imls_34644912768_1233972804/160p30/index-dvr.m3u8

Playlist url for selected quality 1920x1080@60fps (Source) is https://vod-secure.twitch.tv/ca0d74693a95fdfb6491_imls_34644912768_1233972804/chunked/index-dvr.m3u8

Retrieving playlist... done!
Parsing playlist... done!
Number of video chunks: 4026

Starting parallel video chunk download
Number of video chunks to download: 4026
Maximum connection count: 10

Parallel video chunk download is running...

Download of all video chunks complete!

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\redacted\AppData\Local\Temp\TL_699d28df-8cfd-468c-840b-8d839dbd4bd0'... done!

Download task was canceled!
```

**Comment by Franiac** [comment]
So luckily this all happened when I was in vacation and I still am. I take a look at it as soon as possible but I hope you understand that I do not cancel my vacation for TL issues.

SORRY 😄

**Comment by Franiac** [comment]
This VOD and all VODs in the linked closed issues work. This was probably a temporary error with the Twitch servers.

The problem was not downloading the VOD parts but receiving the VOD playlist file from the Twitch servers. This works again apparently. Please confirm!

**Comment by garoto** [comment]
And the VOD playlist always comes from an IP address resolved from the CNAME of `vod-secure.twitch.tv`, as far as my tests have gone.

**Comment by Zar300** [comment]
I'm still getting an immediate error for VODs.

**Comment by cookie1234343** [comment]
same :/

**Comment by Franiac** [comment]
@Zar300 @cookie1234343 It does not help anyone if you are only complaining that it does not work!

PLEASE PROVIDE EXAMPLES!! Preferably non-sub-only VODs that I can test, too.

**Comment by Franiac** [comment]
Reopening for further investigation

**Comment by Zar300** [comment]
Sorry I'll provide a bunch of them cause I've tried almost all and they never work for me

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 447400547
Selected Quality: 1152x648@60fps (Source)
Download Url: https://www.twitch.tv/videos/447400547
Crop Start: Yes (01:00:00)
Crop End: Yes (01:00:30)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\zar\Downloads\20190702_447400547_The Walking Dead.mp4
FFMPEG Path: C:\Users\zar\Pictures\1\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\zar\AppData\Local\Temp\TL_f97b7b3a-0c2d-4cd0-80d8-c05badc3be25

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562251807%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A406308853%2C%22version%22%3A2%2C%22vod_id%22%3A447400547%7D
Signature: 7fb9e43078a1283c410043e6964efe969c19aec2
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\zar\AppData\Local\Temp\TL_f97b7b3a-0c2d-4cd0-80d8-c05badc3be25'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\zar\AppData\Local\Temp\TL_f97b7b3a-0c2d-4cd0-80d8-c05badc3be25'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Zar300** [comment]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 445237672
Selected Quality: 1280x720@60fps (Source)
Download Url: https://www.twitch.tv/videos/445237672
Crop Start: Yes (00:01:00)
Crop End: Yes (00:01:30)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\zar\Downloads\20190627_445237672_Overwatch.mp4
FFMPEG Path: C:\Users\zar\Pictures\1\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\zar\AppData\Local\Temp\TL_acc14e7f-a2bd-456f-9037-0039b6eccea7

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562252183%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A406308853%2C%22version%22%3A2%2C%22vod_id%22%3A445237672%7D
Signature: 9efd579e4aee410bcbf7da05e1bc6172e7d7c387
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\zar\AppData\Local\Temp\TL_acc14e7f-a2bd-456f-9037-0039b6eccea7'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\zar\AppData\Local\Temp\TL_acc14e7f-a2bd-456f-9037-0039b6eccea7'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Zar300** [comment]
The stream is ongoing but I never had a problem downloading ongoing streams

Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 447780030
Selected Quality: 1152x648@61fps (Source)
Download Url: https://www.twitch.tv/videos/447780030
Crop Start: Yes (00:50:00)
Crop End: Yes (01:00:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\zar\Downloads\20190703_447780030_Horizon Zero Dawn.mp4
FFMPEG Path: C:\Users\zar\Pictures\1\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\zar\AppData\Local\Temp\TL_a5f5f5b2-875b-4ee4-b99b-deb289306007

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562252369%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A406308853%2C%22version%22%3A2%2C%22vod_id%22%3A447780030%7D
Signature: ab7655f87c8550728b8cc587606d2df6cebc39c6
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\zar\AppData\Local\Temp\TL_a5f5f5b2-875b-4ee4-b99b-deb289306007'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\zar\AppData\Local\Temp\TL_a5f5f5b2-875b-4ee4-b99b-deb289306007'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Zar300** [comment]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.6

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 445438713
Selected Quality: 1280x720@60fps (Source)
Download Url: https://www.twitch.tv/videos/445438713
Crop Start: Yes (00:02:00)
Crop End: Yes (00:03:00)

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\zar\Downloads\20190628_445438713_Just Chatting.mp4
FFMPEG Path: C:\Users\zar\Pictures\1\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\zar\AppData\Local\Temp\TL_ce524e0c-67b8-4e48-858b-8861ec289caf

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562252846%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A406308853%2C%22version%22%3A2%2C%22vod_id%22%3A445438713%7D
Signature: 5acd2368d30761536b9fce1d0df2508cd0be5ae0
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\zar\AppData\Local\Temp\TL_ce524e0c-67b8-4e48-858b-8861ec289caf'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\zar\AppData\Local\Temp\TL_ce524e0c-67b8-4e48-858b-8861ec289caf'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
@Zar300 All of those work. Cannot be an issue with TL. Maybe somewhat region related.

Where are you located on this planet? Country?

**Comment by Zar300** [comment]
I'm in the US. Not sure why it's still not working. I uninstalled it twice and then reinstalled it and it seems to not work

**Comment by Franiac** [comment]
@Zar300 Like I said it is not an issue inside TL. The server does not respond to the web request for whatever reason. Seems to be a problem in the US from what I can tell right now.

**Comment by Franiac** [comment]
@Zar300 What happens if you copy the following urls into a browser?

[https://vod-metro.twitch.tv/7616806606d581598814_tori_talks_34697838960_1237282035/chunked/index-dvr.m3u8](https://vod-metro.twitch.tv/7616806606d581598814_tori_talks_34697838960_1237282035/chunked/index-dvr.m3u8)

[https://vod-metro.twitch.tv/4c62695c1296c2d832e4_dayebraham_lincoln_34756570240_1240953210/chunked/index-dvr.m3u8](https://vod-metro.twitch.tv/4c62695c1296c2d832e4_dayebraham_lincoln_34756570240_1240953210/chunked/index-dvr.m3u8)

Do you actually get a m3u8 playlist file or do you get a 404 (file not found)??

**Comment by Franiac** [comment]
And another question: Can you watch any of the VODs in the browser???

**Comment by PeryGamerYT** [comment]
i download a index-dvr.m3u8 with the link

**Comment by PeryGamerYT** [comment]
ok, i use a proxy and i try again to download the video and i can now

**Comment by Franiac** [comment]
Ok I found something interesting. The playlist file gets downloaded by TL from

[https://usher.twitch.tv](https://usher.twitch.tv)

If you copy this url into a browser (Firefox in my case) I receive a certificate warning. The certificate is issued to the domain 'https://usher.ttvnw.net' and therefor does not fit. That's the cause of the error.

After checking twitch.tv I realized that the url where Twitch get their playlist files from changed to (who would have expected)

[https://usher.ttvnw.net](https://usher.ttvnw.net)

What I don't understand is why some people (me included) are able to download VODs despite the wrong certificate.

I will change the url in TL to the new one and make a new release (TL 1.5.7) after a little bit of testing.

**Comment by PeryGamerYT** [comment]
ok thank you, when you make the new version?

**Comment by Franiac** [comment]
New release is out. No guarantee that it works because I cannot not test the fail-case since I am not located in the US.

PLEASE LET ME KNOW IF IT WORKS!!!

**Comment by s34nvideos** [comment]
I have the same issue, I downloaded 1.5.7 and the error is still present. I am located in the US. I wanted to download some streams from CEO in Daytona. They have a couple of days left before getting delated, so its not a huge emergency today.

Video I am trying to download: https://www.twitch.tv/videos/445868252

Just gives Status: Error immediately.

From Log:

Creating temporary download directory 'C:\Users\s34n\Downloads\TwitchLeecher\Temp\TL_41f11f5e-89a1-434f-b18e-e35d8936aeb6'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\s34n\Downloads\TwitchLeecher\Temp\TL_41f11f5e-89a1-434f-b18e-e35d8936aeb6'... done!

Download task ended with an error!

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   at TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by PeryGamerYT** [comment]
Download task has been started!

TWITCH LEECHER INFO
--------------------------------------------------------------------------------------------
Version: 1.5.7

VOD INFO
--------------------------------------------------------------------------------------------
VOD ID: 443665520
Selected Quality: 1280x720@60fps
Download Url: https://www.twitch.tv/videos/443665520
Crop Start: No
Crop End: No

OUTPUT INFO
--------------------------------------------------------------------------------------------
Output File: C:\Users\Hector Fabian\Downloads\20190624_443665520_Grand Theft Auto V.mp4
FFMPEG Path: C:\Program Files\Twitch Leecher\ffmpeg_x64.exe
Temporary Download Folder: C:\Users\Hector Fabian\AppData\Local\Temp\TL_3f3dab92-b732-4cc1-a192-a43be29e43da

ACCESS INFO
--------------------------------------------------------------------------------------------
Token: %7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562271511%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3Anull%2C%22version%22%3A2%2C%22vod_id%22%3A443665520%7D
Signature: dbcaae19417b855e9d0e42f81a140d49a6714b94
Sub-Only: No
Privileged: No

Creating temporary download directory 'C:\Users\Hector Fabian\AppData\Local\Temp\TL_3f3dab92-b732-4cc1-a192-a43be29e43da'... done!

Retrieving m3u8 playlist urls for all VOD qualities...

Starting temporary download folder cleanup!
Deleting directory 'C:\Users\Hector Fabian\AppData\Local\Temp\TL_3f3dab92-b732-4cc1-a192-a43be29e43da'... done!

Download task ended with an error!

System.AggregateException: Se han producido uno o varios errores. ---> System.Net.WebException: Error en el servidor remoto: (404) No se encontró.
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   en System.Net.WebClient.DownloadString(Uri address)
   en TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   en TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   en System.Threading.Tasks.Task.Execute()
   --- Fin del seguimiento de la pila de la excepción interna ---
---> (Nº de excepción interna 0) System.Net.WebException: Error en el servidor remoto: (404) No se encontró.
   en System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   en System.Net.WebClient.DownloadString(Uri address)
   en TwitchLeecher.Services.Services.TwitchService.RetrievePlaylistUrlForQuality(Action`1 log, TwitchVideoQuality quality, String vodId, VodAuthInfo vodAuthInfo)
   en TwitchLeecher.Services.Services.TwitchService.<>c__DisplayClass57_0.<StartQueuedDownloadIfExists>b__2()
   en System.Threading.Tasks.Task.Execute()<---

**Comment by Franiac** [comment]
This is bad 😠

I need someone who has the problem and knows how to make web requests and change HTTP headers. Does anyone of you know the tool 'Postman' and how to use it?

I cannot do anything here since I don't have the problem.

**Comment by s34nvideos** [comment]
This is an example URL which the software builds which .NET falls over on:

https://usher.ttvnw.net/vod/445868252?nauthsig=e6f7135cd9bfe4062da8879ccb29e1e7f0a6bc61&nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562272462%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A68659632%2C%22version%22%3A2%2C%22vod_id%22%3A445868252%7D&allow_source=true&player=twitchweb&allow_spectre=true&allow_audio_only=true

Decoded
https://usher.twitch.tv/vod/445868252?nauthsig=e6f7135cd9bfe4062da8879ccb29e1e7f0a6bc61&nauth={"authorization":{"forbidden":false,"reason":""},"chansub":{"restricted_bitrates":[]},"device_id":null,"expires":1562272462,"https_required":false,"privileged":false,"user_id":68659632,"version":2,"vod_id":445868252}&allow_source=true&player=twitchweb&allow_spectre=true&allow_audio_only=true

I am not familiar with the API, but I will gladly change some stuff around if needed

**Comment by Franiac** [comment]
@s34nvideos ok cool... what happens if you put the ENCODED url in the browser? Do you get a 404 instantly? Are you familiar with the browser devtools (F12)?

**Comment by s34nvideos** [comment]
"404 page not found" in Chrome

**Comment by Franiac** [comment]
What do you see under the network tab for this request? I am interested in the response headers (click on "view source" first). mine look like this:

```
HTTP/1.0 200 OK
content-type: application/vnd.apple.mpegurl
x-playlist-request-id: b003f00846e4d2affb37bc59e7b695ff
content-length: 2095
Connection: keep-alive
Cache-Control: no-cache,no-store
```

**Comment by Franiac** [comment]
And can you actually watch the video in the browser?

**Comment by s34nvideos** [comment]
No, no video, just "404 page not found" in the body.

Request URL: https://usher.ttvnw.net/vod/445868252?nauthsig=e6f7135cd9bfe4062da8879ccb29e1e7f0a6bc61&nauth=%7B%22authorization%22%3A%7B%22forbidden%22%3Afalse%2C%22reason%22%3A%22%22%7D%2C%22chansub%22%3A%7B%22restricted_bitrates%22%3A%5B%5D%7D%2C%22device_id%22%3Anull%2C%22expires%22%3A1562272462%2C%22https_required%22%3Afalse%2C%22privileged%22%3Afalse%2C%22user_id%22%3A68659632%2C%22version%22%3A2%2C%22vod_id%22%3A445868252%7D&allow_source=true&player=twitchweb&allow_spectre=true&allow_audio_only=true

Request Method: GET
Status Code: 404 Not Found
Remote Address: 192.108.239.254:443
Referrer Policy: no-referrer-when-downgrade
Cache-Control: no-cache,no-store
Content-Length: 19
Content-Type: text/plain; charset=utf-8
Date: Thu, 04 Jul 2019 00:59:21 GMT
Server: nginx/1.14.1
X-Content-Type-Options: nosniff
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
Host: usher.ttvnw.net
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
nauthsig: e6f7135cd9bfe4062da8879ccb29e1e7f0a6bc61
nauth: {"authorization":{"forbidden":false,"reason":""},"chansub":{"restricted_bitrates":[]},"device_id":null,"expires":1562272462,"https_required":false,"privileged":false,"user_id":68659632,"version":2,"vod_id":445868252}
allow_source: true
player: twitchweb
allow_spectre: true
allow_audio_only: true

**Comment by Franiac** [comment]
@s34nvideos ok, here's another test (i hope i don't stress you out too much 😄):

- go to this channel in chrome: [LINK](https://www.twitch.tv/circon/videos?filter=archives&sort=time)
- open devtools
- go to network tab
- clear the list
- click the first video on the page
- as soon as it starts playing stop the recording in the devtools (red record button in the second row of the devtools)
- right click the "Name" column header and enable "Domain"
- search for the first request with "usher.ttvnw.net"
- post all header information here please

**Comment by s34nvideos** [comment]
I think I have figured it out

What I did notice was, changing the URL to this works:
https://usher.ttvnw.net/vod/445868252.m3u8?etc...

This doesn't
https://usher.ttvnw.net/vod/445868252?etc...

It downloads in Chrome, but gives System.Net.WebException: 'The remote server returned an error: (406) Not Acceptable.' in the source. So I changed the Content-Type, see below.

So I then added:
wc.Headers.Add("Content-Type", "text/plain");

to CreateAuthorizedTwitchWebClient() in TwitchService.cs

-------------

I will still try those steps above if you want me to though, just let me know!

**Comment by Franiac** [comment]
I saw the m3u8 extension in the devtools, too. This is definitely new.

The response is content-type 'application/vnd.apple.mpegurl'. So if you do

`wc.Headers.Add("Content-Type", "application/vnd.apple.mpegurl");`

it should still work, but if 'text/plain' does the job it's all good and more generic I guess. The default request header is 'text/html' if none is added. That is why it does not work without specifying one.

I am going to try reproducing the issue via VPN anyways (in case such an issue happens in the future).

But it's 4 AM now and I'll get some sleep.....

Big THX for the help!!!

**Comment by s34nvideos** [comment]
Anytime! It's almost impossible troubleshooting an issue if you are not experiencing it yourself. Glad to help, I have been using this software for a while now and it's great, so it's the least I could do! So thank you for that!

**Comment by chipdocland** [comment]
Thanks for the application.
I've been using it for months.
very good.
but it has not worked for days.
I hope they can fix it.
it still does not work.
The new update is still not working.
I'm from Mexico, Monterrey,

good luck geniuses.

**Comment by ParasomniaNL** [comment]
Made an account to reply.
Because I solved it for myself by using VPN and then connecting to Hong Kong.
When connected to USA it would not download, and also without VPN it would not download.

Hopefully this will help for some of you :)

**Comment by PeryGamerYT** [comment]
But with VPN the download is slower, well this in my case

**Comment by ParasomniaNL** [comment]
> But with VPN the download is slower, well this in my case

That is often true yes.
I live on a campus in China, so I am used to slow internet but I downloaded 10GB pretty fast :)
But I prefer a slower download over no download as long as it works

**Comment by Franiac** [comment]
The issue is fixed in the master branch. But before I roll this out I want confirmation that it now works so I don't create a second non-functioning TL version!

@s34nvideos Would you be so kind to checkout and sync the master branch, start TL from Visual Studio and see if the problem is now gone? That would be awesome.

The more people test it the better obviously!

**Comment by an3k** [comment]
Tried to download a VOD with 1.5.6
"Downloading" went to the end (100%) then Error was shown.
Updated to 1.5.7
All is working fine again.

**Comment by Zar300** [comment]
Still not working for me even with 1.5.7
I'm just going to wait for a proper update on the program or an alternative

**Comment by Franiac** [comment]
@Zar300 I am not talking about 1.5.7... I am talking about the fixed source code here on GitHub that WILL BE the new (and hopefully working) 1.5.8. I need someone to confirm the new code is working and I hope @s34nvideos will do that if he has time.

**Comment by s34nvideos** [comment]
@Franiac - Sorry, bad timing, I must have went to bed minutes after you originally asked! If it's any consolation, it was the first thing I did today! I grabbed the master branch and ran around 6 URLs that I previously had trouble with, and they all downloaded to completion with no error. I then tested each trouble URL in this thread, and they came down too. So from my end, there is no problem anymore.

@Zar300 - Don't act like there is a better alternative out there ;) I don't think it will hurt you to wait a couple of hours!

**Comment by Franiac** [comment]
@s34nvideos Thx for the test. I will probably pack a new release tomorrow.

And yeah, I also don't get the mentality of people looking for an "alternative" when a tool just doesn't work for a couple days due to changes TL is not even guilty of. Jesus, how important is TL in some peoples lives? 😄

**Comment by chipdocland** [comment]
Tl is the best.
Really the only thing that works.
It has made me earn a lot of money.
as many.
There are people who live thanks to this application.
I wish I never die.
I already worked with a vpn connected from Canada and the application worked for me

greetings from mexico, monterrey XD

**Comment by Franiac** [comment]
This has been fixed in TL 1.5.8! Release is out now.
